### PR TITLE
New "moderator" role

### PR DESCRIPTION
**Pull request by stephanieyshi**
- created a new moderator role: moderator can add/delete resources, add/delete descriptors, CSV upload (update only) (ideally would have moderator only can edit resources that it created, will be a future task)
- edited the routes to restrict the routes that the moderator can access
- edited the nav bar 
- i think we need to do a DB migration or something before we can merge this in

### CODE REVIEW

**Comment by stephanieyshi** [comment]
image

**Comment by stephanieyshi** [comment]
@HanaPearlman should we merge this in with everything else?

**Comment by HanaPearlman** [comment]
This code looks good, although I'm wondering about the functionality where a Moderator can only edit the resources that they uploaded to the site?

**Comment by stephanieyshi** [comment]
merging in!

**Pull request merged**
