### PR TITLE
Navbar reorganization

### PR DESCRIPTION
**Pull request by weronica**
screen shot 2016-03-25 at 10 57 39 pm
screen shot 2016-03-25 at 10 57 49 pm

### CODE REVIEW

**Comment by weronica** [comment]
r @armant

**Comment by armant** [comment]
r @nnarang7

**Comment by weronica** [comment]
Changed again:
screen shot 2016-03-26 at 10 39 15 am

**Comment by nnarang7** [comment]
looks good to me!

**Pull request merged**
